apiVersion: v1                #版本号
kind: ReplicationController #k8s的RC资源
metadata:
  name: elasticsearch 
  labels:
    name: elasticsearch-single #RC的全局唯一标识，名字
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    name: elasticsearch-single
  template:
    metadata:
      name: es
      labels:
        name: elasticsearch-single
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: elasticsearch:5-alpine  #docker 镜像
          # imagePullPolicy: Never
          name: elasticsearch-single
          env:  # 注入到容器内的环境变量
          - name: discovery.type
            value: 'single-node'
          ports:
            - name: es-port
              containerPort: 9200
            - name: es-tran-port
              containerPort: 9300
          volumeMounts:
            - name: es-persistent-storage
              mountPath: /data/es_data
      volumes:
        - name: es-persistent-storage
          emptyDir: {}
