apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-single
  labels:
    name: elasticsearch-single
    kubernetes.io/cluster-service: "true"
spec:
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30009   # 指定一个远程访问端口
  selector:
    name: elasticsearch-single